            <div class="espacio">
                <div class="container">
                <h1 class="huno">Ghost in the Shell: 25 años del nacimiento de una leyenda</h1>
                    <p class="fecha">18 de Noviembre del 2020, 16:21</p>
                    <span class="badge badge-primary">Artículos</span>
                    <span class="badge badge-primary">Anime</span><br>
                    <br>
                    <img src="<?php echo base_url(); ?>/assets/images/aa2.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">        
                    <p>
                    <br>
                    Hoy es un día muy especial para rendir un merecido homenaje a una de las obras más influyentes para toda la comunidad. Así que coged fuerzas y acompañadnos en este viaje a través de un futuro distópico, al devenir de Japón después de la IV Guerra Mundial.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/aa21.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">  
                    <br><br>
                    1989, un jovencísimo Masanori Ota a la edad de 28 años conseguía publicar el primer capítulo de su obra en la Young Magazine, un auténtico éxito que finalizó en 1991 y supuso el inicio de uno de los hitos más grandes de la cultura ciberpunk. Seis años después, concretamente un 18 de noviembre de 1995, Mamoru Oshii junto a Production I.G. decidían darle vida en la pantalla a la obra de Masanori. Una fecha que podría haber quedado como un día corriente o el recuerdo de los fans ante una mala adaptación de esa historia y personajes tan queridos. Aunque nadie era consciente de lo que iban a presenciar, unas salas de cine en las que se hizo historia y se dio forma a uno de los pilares de la animación. Así nacía Ghost in the Shell.
                    <br><br>
                    Un anime que siempre se asocia como máximo estandarte del fenómeno ciberpunk no solamente para el mundo de la animación, sino para toda la industria cinematográfica. Pero antes de nada, seguramente algunos de vosotros os preguntaréis qué significa exactamente este género, de qué trata. De hecho, la propia palabra ya nos da el concepto de forma indirecta: por un lado tenemos su vertiente ciber, haciendo referencia a la robótica, lo cibernético y la corriente pura de ciencia ficción. Por otra parte, tenemos esa esencia tan única como es el fenómeno punk, de rebeldía contra el sistema, contra lo corriente, contra lo normalmente aceptado. Esto es lo que nos muestra a la perfección Ghost in the Shell con su maravillo universo, con la imponente metrópolis de New Port City (新浜市).
                    <br><br>
                    Unos cuantos años antes, la icónica Akira (1988) ya había sentado cátedra a la hora de plantear una ciudad ciberpunk con su mítica Neo Tokyo. Un futuro distópico donde la pobreza y la tecnología eran el pan de cada día. Sin embargo, New Port City no solamente actúa como ambientación o puesta en escena, sino que en muchas ocasiones se convierte en la auténtica protagonista. Esto es algo que podemos apreciar en muchas ocasiones donde quedamos fascinados por los planos generales que se muestran ante nuestros ojos. Vemos una metrópolis totalmente desnuda, sin ningún filtro, sin ningún personaje que nos haga perder la atención en cada detalle de esa ciudad futurista, que a la vez es capaz de mostrar su realidad más dura.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/aa22.png" class="rounded img-fluid mx-auto d-block" width="650" height="300"> 
                    <br><br>
                    Esto lo consigue gracias a la gran aportación de detalles, los cuales poseen tal riqueza y variedad que consiguen otorgar esa identidad tan única a esta metrópolis, nos transportan de lleno a ese universo distópico de la Japón del futuro. Es asombrosa la puesta a disposición, el juego de luces y sobre todo la facilidad con la que logra captar el ambiente opresivo y lúgubre en unos pocos planos. En nuestra mente conseguimos imaginarnos la vida, la rutina diaria de sus gentes en ese mundo tan difícil para una parte significativa de la población. A veces, incluso la trama principal se relega a un segundo plano, provocando en el espectador la necesidad de conocer más acerca del trasfondo de ese mundo.
                    <br><br>
                    Creemos que cuando una obra logra esta reacción, aunque solo sea una vez, es sinónimo de que el trabajo se ha hecho más que bien, porque has marcado, has incentivado a la gente a indagar sobre tu creación. Porque Ghost in the Shell es tan única e irrepetible que consigue que el ser humano sea incapaz de no rendirse ante la belleza de la decadencia.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/aa23.png" class="rounded img-fluid mx-auto d-block" width="650" height="300">
                    <br><br>
                    Sin embargo, esta personalidad tan especial no solamente se circunscribe a un único plano, sino que ya desde el primer momento con su opening nos damos cuenta de lo que estamos a punto de presenciar. Un inmenso mar de códigos de programación con ese característico tono verdoso de las antiguas computadoras aparece en pantalla. Aunque lo que más llama la atención es lo que está ocurriendo entre bastidores, donde observamos un extraño cerebro introduciéndose dentro de una cavidad, concretamente en lo que aparenta ser un cíborg. Una chica descubre su mirada gélida al mundo, al espectador, la Mayor Motoko Kusanagi hace acto en escena y un fundido en negro nos adelanta que nada volverá a ser como antes, ya estamos dentro de esta fantasía ciberpunk.
                    <br><br>
                    La presentación y la personalidad de esta empleada de la sección 9 de antiterrorismo daría para cubrir ríos de tinta por una sencilla razón: fue la primera mujer en tomar el protagonismo en una obra de esta temática. No observamos a un personaje marginado, antisocial y en definitiva, un ser humano tal y como lo concebimos, sino que estamos viendo como un auténtico cíborg, que solo mantiene la conciencia de una vida pasada y es la encargada de llevar el protagonismo de la cinta.
                    <br><br>
                    Entrando en comparaciones, podemos apreciar diferencias con Akira (1988) o, de forma más directa, con la obra de culto en occidente y antecesora a nuestra protagonista de hoy, Blade Runner (1982). Debates históricos al margen, el personaje de Harrison Ford se presenta como hombre y ser humano, algo que es absolutamente lo contrario al personaje de la Mayor. Es tal la magnitud de esta mujer que, tal y como vimos en anteriores homenajes, como a la figura de Satoshi Kon, la influencia que tiene en películas tan distintas en planteamiento, pero hermanas en su esencia como fue el caso de la archiconocida Matrix (1999), resultan demoledoras.
                    <br><br>
                    Las hermanas Wachowski en numerosas entrevistas han reconocido que cogieron muchas referencias e ideologías no solo del planteamiento del universo distópico que propone Ghost in the Shell, sino de la presentación de su protagonista, el cual está claramente basado en el modelo de Kusanagi. Otro ejemplo más de como los pilares de la animación en muchas ocasiones trascienden al plano general y se convierten en referentes para toda una generación, se hacen eternos.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/aa24.png" class="rounded img-fluid mx-auto d-block" width="650" height="300">
                    <br><br>
                    A pesar de que la obra de Oshii haya inspirado a muchas otras, se sigue diferenciando tanto del resto gracias a su crudeza, a su simpleza y al no tratar de ocultar su identidad. Nos muestra de manera clara y directa el dilema filosófico y existencial que quiere transmitir ¿Cuánto queda de ser humano en Kusanagi? ¿Es una realidad artificial al completo? ¿Realmente sabemos qué somos nosotros? Dudas, cuestiones, caos y multitud de factores que ya son algo inherente al planteamiento de una historia ciberpunk, y que se potencian todavía más con el transcurso de los acontecimientos y la aparición del villano de esta película, el Titiritero. Una figura que en un principio no se nos muestra con una forma corpórea y sin embargo, de forma paradójica, es probablemente el momento en el que más se pone contra las cuerdas nuestra concepción habitual de qué es un ser humano.
                    <br><br>
                    Sobre la mesa tenemos el concepto de identidad y si esa IA es capaz de poseer un ghost, una esencia única a ese ser, lo que los humanos de la época aseguran que traza la línea de separación entre artificial y realidad. De hecho, el final es una acumulación de todas estas preguntas que se va realizando el espectador y que se resuelven de una forma tan magistral que indudablemente podemos categorizar este desenlace como uno de los más completos y formidables que hemos tenido el orgullo de presenciar en cualquier medio de este arte.
                    <br><br>
                    Podríamos estar muchas horas profundizando sobre la inmensa cantidad de símbolos, alegorías y referencias que observamos en estos compases finales que tantos misterios aguardan tras de sí. Sin embargo, creemos que lo mejor en una fecha tan señalada como este 25.º aniversario es intentar incentivar a todas aquellas personas que todavía tienen pendiente su primer visionado a que se adentren de pleno en todo el torrente de emociones que nos transmite Ghost in the Shell y, para los veteranos, nunca viene mal viajar otra vez a este Japón tan especial. 
                    <br><br>
                    Una auténtica obra de culto tan importante para esta industria que tanto queremos y el género ciberpunk.  
                    </p>
                    <br><br>