         <div class="espacio">
                <div class="container">
                <h1 class="huno">Retro: Yoshi's Island</h1>
                    <p class="fecha">5 de Noviembre del 2020, 17:05</p>
                    <span class="badge badge-primary">Artículos</span>
                    <span class="badge badge-primary">Videojuegos</span><br>
                    <br>
                    <img src="<?php echo base_url(); ?>/assets/images/av2.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">        
                    <p>
                    <br>
                    <p>¡Hola! Qué gusto verte de nuevo por aquí. Ha llegado ese momento de la semana en el que nos detenemos a analizar un poco aquellos juegos que nos iniciaron en este pasatiempo o que marcaron nuestra historia gamer de alguna manera.
                    <br><br>
                    Super Mario World causó revuelo por varias razones: se trató del título principal de lanzamiento del Super Nintendo, fue el sucesor del que para muchos es el mejor juego de Mario de todos los tiempos y nos presentó a un nuevo personaje que hizo mancuerna perfecta con el héroe, además de ganarse el corazón de los seguidores de la mascota de Nintendo.
                    <br><br>
                    Son muchos los casos en los que el patiño supera al protagonista y se abre camino por su cuenta, aunque la fórmula no siempre funciona. Es el caso de Mi villano favorito, en donde los Minions se llevaron casi todos los honores, pero cuando optaron por hacer una cinta independiente de Gru, los resultados no fueron buenos, al menos desde mi punto de vista. Con el éxito que trajo Yoshi para la Gran N después de haberlo incluido en Super Mario World, la cosa no podía quedarse ahí. El movimiento lógico era desarrollar un juego nuevo que incluyera al dinosaurio sí o sí pero, ¿cómo explotarlo después de la gran aceptación que tuvo como ayudante de Mario?
                    <br><br>
                    El nombre oficial del título que esta semana nos ocupa es Super Mario World 2: Yoshi’s Island, pero la forma de presentarlo en la pantalla del título dice mucho. Era necesario hacer una conexión con el título anterior que tan buenos frutos dio a Nintendo, pero ahora el mayor énfasis debía estar en Yoshi, por lo que el subtítulo se hizo de manera mucho más llamativa. El protagonista no era Mario, aunque sí funcionó como gancho. La responsabilidad ahora recaía sobre la espalda del dinosaurio verde, literalmente.
                    <br><br>
                    En términos de historia, podríamos decir que Yoshi’s Island es el Ocarina of Time de la saga, ya que nos cuenta los orígenes de los hermanos Mario, quienes estelarizan una historia que podría convertirse en episodio de La Rosa de Guadalupe. Una cigüeña volaba tranquila con 2 bultos en el pico. De repente, Kamek se impactó con ella y se robó al pequeño Luigi. Mario cayó al vacío y fue a dar a la isla de los Yoshi, donde fue rescatado milagrosamente por uno de ellos. Analizando la situación y dándose cuenta de que la cigüeña traía un mapa, los coloridos dinosaurios deciden llevar a Mario bebé a su destino usando un sistema de relevos. El desenlace puedes adivinarlo sin jugar el juego, y en este caso importa mucho más el camino que el destino.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/av21.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">    
                    <br><br>
                    El Super Nintendo ya era terreno conocido y sus capacidades estaban siendo muy bien explotadas en 1995, año en que apareció Yoshi’s Island. Para ese entonces ya contábamos con un catálogo bastante robusto, de modo que la máquina de 16 bits de Nintendo gozaba de muy buena salud. Como ya todos sabemos, la prioridad de la gran N al desarrollar sus propuestas es que éstas sean divertidas, memorables y que lleven al jugador a desear seguir jugando a pesar de haber llegado a la pantalla final. Yoshi’s Island es un deleite en todos sentidos. Lleva casi al límite a la consola y constituye una experiencia muy grata, así como un serio desafío para los que les gusta sacar el 100 % en todo.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/av22.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300"> 
                    <br><br>
                    El mapa se presenta como un pergamino en el que distintos Yoshis marcan los niveles, mientras que los mundos se distribuyen en pestañas en la parte superior. Cada uno cuenta con 8 niveles, en los cuales debes obtener el mayor puntaje posible si es que quieres destapar el nivel especial, que es el más difícil de cada mundo. Cada etapa tiene su nombre, lo cual me parece un gran detalle que ya habíamos visto en Super Mario World. Para obtener el 100 %, debes llegar al final de cada nivel con 30 estrellas, 20 monedas rojas y 5 flores. Todos estos elementos están esparcidos en cada nivel y, conforme vas avanzando, se va volviendo más difícil encontrarlos. En la pantalla de pausa puedes ir verificando tu avance y ver qué te falta, además de tener acceso a ciertos power ups que pueden ayudarte cuando un nivel aprieta demasiado.
                    <br><br>
                    La mayor dificultad está en las estrellas, ya que, si recibes daño, pierdes algunas y debes recuperarlas para llegar de nuevo a la marca de 30. Por si esto fuera poco, debes soportar el incesante llanto de Mario bebé. Este detalle es lo único que no me gusta de Yoshi’s Island. De verdad es insoportable. Entiendo que el juego debe avisarte que tienes recuperar al bebé y estresarte un poco para conseguirlo, pero ese llanto taladra los oídos despiadadamente. Debes ser muy cuidadoso para que el pequeño nunca se separe de ti, porque de lo contrario tendrás que soportar sus berridos.
                    <br><br>
                    Durante muchos momentos es imposible no acordarse de Super Mario World, sobre todo en los castillos, pero la variedad y mecánicas de juego de Yoshi’s Island superan por mucho las de su antecesor. Además de los tradicionales saltos que caracterizan a los juegos de plataformas, Yoshi debe valerse de sus huevos para conquistar cada nivel. Cada vez que el dinosaurio devora con su lengua a algún enemigo, puede hacer una digestión ultrarrápida y producir uno de los ya mencionados blanquillos, los cuales debe lanzar para derrotar enemigos, destapar una nube de bonus o alcanzar algún objeto. Si te faltan huevos y no hay enemigos que puedas tragar para fabricarlos, existen puntos donde hay bloques que puedes golpear cuantas veces quieras hasta llenar tu reserva de proyectiles ovoides.
                    <br><br>
                    Además de obligarte a lanzar proyectiles al por mayor, Yoshi’s Island introdujo las transformaciones; es decir, en ciertas zonas, Yoshi puede convertirse en distintos vehículos con los que puede alcanzar áreas u objetos que en su forma normal son inaccesibles. Estos momentos, aunque son breves, le dan frescura al juego y ofrecen una nueva manera de ver los niveles. Me gusta particularmente la parte en la que usas un tren y avanzas sobre vías trazadas en la pared. También me parece muy creativa la parte en la que usas un carrito y debes presionar B para estirarte y evitar a los enemigos. Creo que es un guiño al rumbo que Yoshi tomaría más adelante con Yoshi’s Story y demás entregas subsecuentes. De por sí, Yoshi’s Island ya tiene un tono bastante infantil, pero eso no debe ser motivo para verlo como un juego sencillo, porque para nada lo es.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/av23.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300"> 
                    <br><br>
                    Hablando de la dificultad, los niveles especiales están hechos para probar la paciencia y resistencia de cualquiera. No se trata sólo de pasarlos, sino que también debes obtener un puntaje de 100 para que el Monk que hay dentro de ti se sienta completamente satisfecho. Me parece que es una muy buena forma de explotar la experiencia de juego en general y una muy buena recompensa para aquellos que, con el sudor de su frente, consiguen la puntuación máxima en cada nivel. Como dijimos, es regla que los juegos de esta franquicia tengan, por lo menos, un nivel que te saca de quicio.
                    <br><br>
                    Yoshi’s Island es una gran secuela de aquel título que nos abrió las puertas de la nueva generación, por lo menos del lado de Nintendo. Cerca del final de aquella etapa de 16 bits, Nintendo se lució con varias joyas para su consola. Esta aventura de Yoshi sin duda es una de ellas y no puedes dejar de jugarla si es que no lo has hecho. Te recomiendo que prestes atención especial a las expresiones faciales de los personajes, ya que están muy bien logradas y te comunican a la perfección el sentir de cada uno.
                    </p>
                    <br><br>
   
