
            <div class="espacio">
                <div class="container">
                <h1 class="huno">RESEÑA - Spider Man Miles Morales</h1>
                    <p class="fecha">17 de Noviembre del 2020, 15:00</p>
                    <span class="badge badge-primary">Reseñas</span>
                    <span class="badge badge-primary">Videojuegos</span><br>
                    <br>
                    <img src="<?php echo base_url(); ?>/assets/images/rv2.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">        
                    <br>
                    <p>Marvel’s Spider-Man marcó un antes y un después en el género de superhéroes en los videojuegos. Tomó nota de los grandes triunfos de la serie Arkham de Batman, así como inspiración de las mejores adaptaciones pasadas del tejerredes, para crear una obra casi perfecta que todo fanático de Spider-Man o de las videojuegos en general puede apreciar. Por eso mismo, había altas expectativas rodeando a Spider-Man: Miles Morales, una pseudo-secuela del título original que nos ponía en el papel del epónimo personaje en lugar de Peter Parker mientras intenta forjar su propio camino como héroe. Ahora que hemos tenido tiempo de ver cómo Miles Morales lidia con ser el único protector arácnido de Nueva York, podemos decir que la mayoría de esas expectativas no sólo fueron cumplidas, sino hasta superadas. No obstante, hay pequeños detalles que dejan a Spider-Man: Miles Morales un poco atrás de su predecesor, incluso cuando en un sentido técnico llega a ser notablemente superior.</p>
                    
                    <p>La premisa de Spider-Man: Miles Morales es sencilla. Quizá demasiado si somos honestos. Es Navidad, las calles están repletas de nieve y Peter Parker va a tomarse un descanso de ser Spider-Man y dejar en manos de su protegido, Miles Morales, la responsabilidad de cuidar Nueva York en su ausencia. Paralelo a esto, Roxxon, un corporativo enorme que claramente no tiene intenciones altruistas, está comenzando a apoderarse del distrito de Harlem, instigando un conflicto ideológico y político con la madre de Miles, Río, candidata a funcionaria del distrito. Es obvio que Roxxon será el primer gran reto para Miles en el rol de Spider-Man, y para hacerle frente deberá conciliar su pasado y presente, así como decidir qué clase de hombre quiere ser en el futuro. </p>
                    
                    <img src="<?php echo base_url(); ?>/assets/images/rv22.png" class="rounded img-fluid mx-auto d-block" width="650" height="300">   
                    <br>
                    <p>A pesar de que Spider-Man: Miles Morales nos deja explorar toda Nueva York como lo hizo su predecesor, el corazón de la historia está en Harlem y su conflicto con Roxxon. Al tratarse entonces de una campaña de menor escala, toda la acción se siente mucho más concentrada, tanto en un sentido narrativo como jugable. El resultado es una historia que hace que Miles aprenda algo que nosotros y Peter Parker hemos sabido por mucho tiempo: con un gran poder viene una gran responsabilidad.</p>
                    <p>
                    El único problema que encontramos con esto es que la razón por la que Peter no está en la ciudad se siente tonta, ¿por qué dejaría una responsabilidad tan grande en los hombros de alguien que apenas está aprendiendo a usar sus poderes? Quizá pueda justificarse diciendo que Peter tomó el rol de Spider-Man cuando tenía la misma edad de Miles, pero la ejecución de la ausencia del Spider-Man original se siente forzada y extraña, especialmente cuando recibimos llamadas de él a mitad de la campaña ofreciendo venir a ayudarnos si lo necesitamos. Si la ausencia de Peter hubiera sido la culpa de Miles, como una consecuencia de no confiar en sí mismo o un accidente combatiendo el crimen, tendríamos el mismo escenario y una premisa mucho más emotiva. Probablemente es algo que Insomniac está guardando para una historia futura, pero nos hubiera gustado verla aquí como una referencia a la película de Into the Spider-Verse. La escala más pequeña de la historia, además, aunque hace sentir todo más personal también demerita la experiencia en comparación al juego original, pues hay menos cosas por hacer y no se siente que se aproveche el enorme mapa en su máximo potencial narrativo.</p>
                    
                    <img src="<?php echo base_url(); ?>/assets/images/rv23.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">   
                    <br>
                    <p>Continuando con las comparaciones entre este y el juego original, pero ahora en un aspecto técnico, Miles se controla muy parecido a Peter, pero hay animaciones específicas para Miles cuando está columpiando y combatiendo que lo distinguen del Spider-Man más maduro. No sabemos cómo decirlo, Miles tiene mucho estilo. La gracia de sus acrobacias es todo un deleite de ver, y en su mejor momento pueden competir con las secuencias de Into the Spider-Verse. Además, los poderes especiales de Miles, como su Venom Strike, crean nuevas posibilidades de combos, y conforme más nos acostumbramos a implementarlos en combate, más podemos ver a Miles como un héroe separado de Peter y no meramente como el mismo personaje portando un traje distinto. No vamos a mentir: hay momentos en los que jugar como Miles se siente más divertido que cuando jugábamos con Peter en el título original.</p> 
                    
                    <p>Una de las cosas que no se nos puede olvidar mencionar es que Spider-Man: Miles Morales es uno de esos selectos títulos que fueron diseñados para acompañar el lanzamiento del PlayStation 5. Aunque el juego también está disponible para PlayStation 4, sentimos que Spider-Man: Miles Morales debe de experimentarse obligatoriamente en el nuevo PlayStation. Hay dos sólidas razones para ello: el control Dual Sense y el increíble potencial gráfico de la nueva generación de consolas.</p> 

                    <p>
                     Aquí se aprovecha muy bien la tecnología háptica del control Dual Sense, haciéndonos sentir vibraciones leves que simulan el movimiento del metro en la secuencia introductoria del juego, hasta unas un poco más fuertes que pretenden hacernos sentir el impacto de los golpes eléctricos de Miles. Simplemente, la incorporación del Dual Sense como dispositivo de inmersión es brillante. Por otro lado, el PlayStation 5 nos da dos modos de juego: Modo Fidelidad y Modo Desempeño. El Modo Fidelidad nos deja ver con lujo de detalle las nuevas fronteras exploradas por los gráficos del PlayStation 5, con un 4K nativo, ray-tracing por todos lados y un framerate cinemático. El Modo Desempeño, por otro lado, sacrifica un poco el encanto visual, pero se nos entrega un framerate fijo de 60FPS. Además, los tiempos de carga son prácticamente inexistentes en el nuevo PlayStation y contribuyen a un saludable flujo de la acción.
                    </p>
                    
                    <img src="<?php echo base_url(); ?>/assets/images/rv24.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">
                    <br>   
                    <p>Con todas sus fichas sobre la mesa, Spider-Man: Miles Morales se convierte en justo lo que necesitábamos para alegrar un año tumultuoso. No es la siguiente evolución de lo que vimos en Marvel’s Spider-Man, pero sí es el complemento perfecto a la obra original, así como una pequeña probada de todo lo que podemos esperar cuando Insomniac finalmente nos muestre el siguiente capítulo en las aventuras de Peter Parker, y ahora también, de Miles Morales.  
                    </p>

   