   <div class="espacio">
                <div class="container">
                <h1 class="huno">Retro: Super Castlevania IV</h1>
                    <p class="fecha">29 de Octubre del 2020, 11:00</p>
                    <span class="badge badge-primary">Artículos</span>
                    <span class="badge badge-primary">Videojuegos</span><br>
                    <br>
                    <img src="<?php echo base_url(); ?>/assets/images/av3.jpeg" class="rounded img-fluid mx-auto d-block" width="650" height="300">        
                    <p>
                    <br>
                    <p>Te doy la más cordial bienvenida a un #ViernesRetro más. Espera, no, no es cualquier #ViernesRetro, porque hoy estaremos hablando de uno de los títulos más importantes y valiosos para mí. Está dentro de mi Top 10 personal de todos los tiempos, además de que es un puente hacia recuerdos muy gratos. No es sólo cosa mía, sino que ha aparecido en varias listas de los videojuegos más destacados de la historia.
                    <br><br>
                    Super Castlevania IV es uno de los mejores ejemplos de una excelente transición de una generación de consolas a la siguiente. Konami nos deleitó con una gran trilogía en el NES, a pesar de que, para muchos, Simon’s Quest sea una especie de oveja negra. La primera entrega se caracterizó por su dificultad; la segunda, por la confusión que causó y lo críptico de sus pistas (por lo menos en la versión occidental), mientras que la tercera perfeccionó el modo de juego y representó un cierre muy digno de la saga vampírica por excelencia en la era de los 8 bits.
                    <br><br>
                    En Super Castlevania IV vi por primera vez esa icónica cortinilla de Konami acompañada del característico efecto de sonido. Después comenzó una música tétrica, el cuadro mostró un desgastado muro plagado de bichos y algunas vainas espinosas. El vuelo de una serie de vampiros y el estruendo de varios truenos alteraron el momento y así apareció el título del juego con un diseño increíble y el prefijo SUPER que en aquel entonces era una obligación. Tiene que tener historia, pensé, así que no presioné START y esperé unos segundos. En uno de los momentos más atmosféricos del juego, un rayo destruyó una tumba y, con mi limitado inglés de aquel entonces, leí entre tinieblas que cada 100 años regresa la amenaza de Drácula, pero que el temible conde es cliente de los Belmont, una familia que cada siglo le ha hecho ver su suerte.
                    <h4 class="huno">SENTIDO DE PERTENENCIA</h4>
                    <hr class="lineaDiv">
                    Para efectos de este artículo, volví a Super Castlevania IV a través de Castlevania Anniversary Collection en Nintendo Switch. Mi rutina es la siguiente: voy a la pantalla de opciones y ajusto el botón de ataque especial en el botón A en lugar del R; regreso a la pantalla de inicio y selecciono START; aquí el juego te da la oportunidad de poner tu nombre, lo cual me parece un detalle muy especial. Es el único momento en el que tienes oportunidad de personalizar algo. El nombre que pongas no tiene relevancia en cuanto al desarrollo de la historia, los niveles o cualquier otra cosa, pero creo que Konami lo incluyó con la intención de hacerte sentir parte de la aventura. Todos sabemos que el personaje que usas se llama Simon Belmont, pero en este pequeño mundo creado por el vínculo entre juego y jugador, puede llamarse como quieras. Puedes ser el héroe que salva el día. Dicho sea de paso, yo siempre pongo SIMON porque soy muy ñoño. Por otro lado, aquí no funciona poner HELP ME para iniciar con 10 vidas, sorry.
                    <br><br>
                    <h4 class="huno">UN LÁTIGO QUE NO SÓLO SIRVE PARA ATACAR</h4>
                    <hr class="lineaDiv">
                    Una de las grandes mejoras de Super Castlevania IV respecto a sus predecesores es la movilidad que le dieron a Simon. Ahora es posible golpear con el látigo en 8 direcciones, a la vez que se tiene mayor control al subir o bajar escaleras. Se puede caminar agachado, con lo que se pueden evitar algunos peligros. Si se deja presionado el botón de ataque, es posible jugar con el látigo como si fuera una cuerda o bien usarlo como escudo protector. Se trata del uso más versátil que se le ha dado a esta legendaria arma y es una tristeza que eso no se haya conservado en entregas posteriores. Volvieron las clásicas armas como el hacha, el reloj, el cuchillo y el agua bendita, pero la mejor sigue y seguirá siendo la cruz búmeran. Es el arma que nadie quiere perder. Con tal de conservarla, memoricé los lugares en los que, al golpear una vela, aparece otra arma; esto con la intención de evitarla a toda costa. Lo mejor viene cuando tomas el multiplicador II o el III, ya que puedes lanzar más de un búmeran a la vez y causar gran daño.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/avv1.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">    
                    <br><br>
                    Además de las cualidades ya mencionadas, el látigo te sirve para colgarte de argollas que aparecen en algunos niveles. Se siente muy bien balancearse cual Tarzán y alcanzar el otro lado del abismo. También puedes quedarte colgado y esperar el momento idóneo para balancearte y saltar. Esta mecánica abrió muchas posibilidades para diseño de niveles y fue muy bien aprovechada.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/av31.jpeg" class="rounded img-fluid mx-auto d-block" width="650" height="300"> 
                    <br><br>
                    Finalmente, al terminar cada nivel esta multifacética arma sirve para lucirse un poco. Al derrotar al jefe en turno, aparece un cristal que hay que tomar para cerrar la escena, pero al hacerlo la imagen se congela, por lo que siempre busco la manera de tomarlo en una posición heroica que quede plasmada para la posteridad. Seguramente tú también lo haces.
                    <h4 class="huno">SACÁNDOLE PROVECHO AL MODE 7</h4>
                    <hr class="lineaDiv">
                    A pesar de ser un título casi de lanzamiento para el Super Nintendo, Super Castlevania IV hace gala de las capacidades de la máquina como pocos juegos lo hacen. Se nota el extremo cuidado que le pusieron a cada nivel, las capas de profundidad que cada uno tiene y la variedad de entornos que se puede disfrutar en cada momento. Hay cráneos en los muros que te siguen con la mirada, manos que salen del suelo y sujetan tu pierna, monstruos que salen de la pared y pinturas aparentemente inofensivas de las que sale una mano que te toma del brazo. Por detalles no paramos.
                    <br><br>
                    Aunque desde el inicio de la vida de la consola Nintendo presumió su capacidad gráfica, especialmente con F-Zero, en Super Castlevania IV esas cualidades pudieron lucirse mucho más. Como mencioné, cada nivel tiene su ambientación muy bien lograda, pero hay 2 que destacan no sólo por las gráficas como tales, sino por la forma en la que el jugador debe interactuar. Me refiero, en primer lugar, al nivel 4-2, en el que debes sujetarte a una argolla con tu látigo y esperar que el escenario gire para alcanzar una plataforma y tener acceso a la siguiente sección. Antes de eso, debes deshacerte de algunas cabezas de medusa, que son los enemigos más molestos no sólo de esta entrega, sino de la saga completa. La sorpresa no termina ahí, porque en el siguiente bloque (4-3) debes avanzar por un túnel giratorio en el que aparecen esqueletos que intentan detenerte. Debo confesar que, las primeras veces que jugué este nivel, me costó trabajo concentrarme en los enemigos y en las velas por lo maravillado que quedé con los gráficos.
                    <br><br>
                    Otra cosa que me llama la atención es que estas 2 etapas no son las únicas razones por las que podemos decir que el trabajo gráfico y de diseño en Super Castlevania IV es sobresaliente. Los primeros 5 niveles se desarrollan en el exterior, mientras que los siguientes son dentro del castillo de Drácula. En este caso también la ambientación es espectacular. Si ya estaba sorprendido por la escena del túnel giratorio, con la de los candelabros gigantes que se mueven como péndulos y en los que debes saltar para llegar al otro lado ya no supe de mí. Super Castlevania IV es un juego que no te deja acostumbrarte a nada, sino que constantemente te presenta cosas que le dan mucha frescura a la experiencia.
                    <br><br>
                    Al finalizar el nivel 7, sentí que estaba haciendo algo mal, porque de pronto el suelo comenzó a temblar, se abrió y caí. ¿Qué estaba pasando? Estaba entrando a las catacumbas del nivel 8. Las veces que he intentado terminar el juego sin perder una sola vida, esta escena es la que me ha echado todo a perder. Está llena de picos por todos lados, pero eso no es lo peor. Hay una parte al final en la que debes calcular la aparición y desaparición de una serie de bloques para ir saltando y llegar al otro lado. No puedo contar las veces que me he caído ahí, tirando por la borda mi partida perfecta.
                    <br><br>
                    <img src="<?php echo base_url(); ?>/assets/images/av32.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300"> 
                    <br><br>
                    Creo que a todos nos gusta ver lo que sucede una vez que terminamos un juego. En ocasiones puede ser un total fiasco, pero en otras los programadores te dan un regalo de despedida bastante agradable. Este es el caso de Super Castlevania IV, cuya secuencia final no hace más que bajar la cortina como los grandes, con una gran cereza en el pastel más delicioso que jamás hayas probado. Simon sostiene su látigo y a la distancia observa cómo el castillo de Drácula se desploma al amanecer. El sol en el fondo te da una sensación de tranquilidad, de un nuevo comienzo, de una nueva oportunidad. Es una imagen que se queda en la memoria y tu premio por haber llegado hasta ese punto. ¿Te sientes como un héroe? Tienes todo el derecho, porque el camino ha sido largo y ahora sólo queda disfrutar, al menos durante los siguientes 100 años, de la paz que ahora se respira en estas tierras. Como si fuera un álbum de recuerdos, los créditos corren mostrándote momentos de cada nivel y eso irremediablemente te hace suspirar, trayendo a la memoria todos esos obstáculos que has tenido que superar. Es una maravilla de principio a fin aderezada con una melodía llena de añoranza y triunfo.
                    </p>
                    <br><br>
  