            <div class="espacio">
                <div class="container">
                <h1 class="huno">RESEÑA – Yakuza Like a Dragon</h1>
                    <p class="fecha">18 de Noviembre del 2020, 20:57</p>
                    <span class="badge badge-primary">Reseñas</span>
                    <span class="badge badge-primary">Videojuegos</span><br>
                    <br>
                    <img src="<?php echo base_url(); ?>/assets/images/rv1.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">        
                    <br>
                    <p>La franquicia de Yakuza tiene una tradición enorme en la industria de los videojuegos. Varios son los títulos numerados y reboots que han formado este mundo abierto donde el crimen organizado en Japón ha servido para dotarnos de historias tan épicas como irreverentes. Sin embargo, al ser una saga con un legado tan grande, pocos son los jugadores nuevos que se pueden aproximar a esta saga tan consolidada, o eso es lo que creíamos hasta que probamos Yakuza: Like a Dragon, un reboot que parte de la saga pero nos lleva a una locura JRPG, nuevo género y enfoque muy digno de probarse especialmente para aquellos que nunca habían jugado un Yakuza antes.</p>
                    
                    <p>Like a Dragon no se conecta con los acontecimientos de los demás juegos de la saga, pero, a pesar de que este juego se presenta como una cosa muy irreverente y difícil de tomar en serio, al final la franquicia consiguen enseñarnos que incluso en la narrativa más boba y chusca, la historia que están alrededor de la Yakusa no es una broma. Veremos chistes, sí, pero también nos veremos envueltos en un drama digno de la serie.</p>
                    
                    <img src="<?php echo base_url(); ?>/assets/images/rr1.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">   
                    <br>
                    <p>Nos pondremos en los zapatos y rojizo traje de Ichiban Kasuga, un matón de bajo rango de una familia yakuza de poca monta de Tokio, el cual tuvo que cumplir una pena en prisión de 18 años por un delito que no cometió. Sin perder nunca la fe, cumple su pena a regañadientes y regresa a la sociedad para descubrir que nadie lo esperaba afyera y que su clan ha sido destruido por el hombre al que más respetaba. Ichiban se propone a descubrir la verdad de la traición sufrida por su familia y recuperar su vieja vida, y para ello recluta a lo mejor que encontró, o sea un grupo de marginados de la sociedad: Adachi, un policía sin escrúpulos, Nanba, un ex enfermero sin hogar, y Saeko, una camarera con una misión personal siempre en mente. Juntos, se ven envueltos en un conflicto que se gesta bajo la superficie de Yokohama, y deberán superarse para convertirse en los héroes que nunca esperaron ser.</p>
                    <p>
                    Bueno, con excepción de Kasuga, que dentro de toda la tragedia que ha vivido, ha encontrado en los videojuegos, y en especial en la franquicia de Dragon Quest, el escape necesario para conllevar toda su tragedia. Y conforme más vayamos jugando más nos daremos cuenta de que Kasuga lo único que busca es redención siendo uno de esos héroes que ha admirado en sus juegos JRPG favoritos. Por ello es que Yakusa, de forma un tanto poética, termina convirtiéndose en un RPG por turnos, una experiencia hecha a la medida de Kasuga. Como si el cambio de género fuera por la psique de nuestro protagonista, y por detalles como este es que la historia del juego no tiene desperdicio y, al contrario, nos saca una risas sinceras que siempre se agradece jugando videojuegos.</p>
                    
                    <img src="<?php echo base_url(); ?>/assets/images/rr2.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">   
                    <br>
                    <p>En cuanto al tema jugable, como ya dijimos, ahora estamos ante un RPG por turnos en contraste al combate más fluido y rápido que ya conocíamos de la saga. Esto, más que ser un problema, es una bocanada de aire fresco a la serie, no solo porque sea distinto y fresco, sino porque simplemente funciona tan bien que es divertido y hasta burlón. Como si se burlara de todo los clichés que se pueden sacar del género y ridiculizarlo al máximo nivel. Esto más que sonar mal es un detalle hilarante y divierte en cada encuentro. Eso sí, puede que explorando las calles de Yokohama nos topemos con demasiados encuentros, más de los que nos gustaría, por lo que puede, a veces, hartar. Sin embargo esto se puede arreglar viajando en taxi, pero nos estaríamos perdiendo de experiencia y dinero extra que podemos obtener en la calle peleando.</p> 
                    
                    <p>El combate es sencillo de dominar y muy divertido, con los esquemas normales de un juego del género. Ataques especiales y una predisposición por interactuar con el entorno, característica típica de la serie. También tiene un sistema de parry con lo que hará que la atención que tengamos en el combate sea la mayor y se sienta un ritmo dinámico y muy exigente a la hora de pelear, sobre todo con los contrincantes con más poder.</p> 
                    
                    <img src="<?php echo base_url(); ?>/assets/images/rr3.jpg" class="rounded img-fluid mx-auto d-block" width="650" height="300">
                    <br>   
                    <p>Con un apartado visual que presume la entrada a una nueva generación de consolas, al menos del lado del Xbox Series X/S y PC como exclusivo por  tiempo limitado, Yakuza Like a Dragon es un juego destacable y que sin duda vale la pena invertirle las más de 50 hora que nos puede tomar pasarlo. Cualquier fanatico de la saga puede jugarlo sabiendo que vivirá una experiencia nueva y refrescante en este gran mundo de mafiosos japoneses, pero para los neófitos en la serie, sean bienvenidos al mundo de Yakuza con esta peculiar experiencia, seguramente será una entrada que los dejará queriendo saber mas de esta querida y bien valorada franquicia. 
                    </p>
